[versions]
anvil = "2.4.4"
kotlin = "1.8.10"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.5.0"
androidxComposeCompiler = "1.4.3"
androidx-activity = "1.3.1"
jbCompose = "1.3.1"
lint = "30.4.2"
zipline = "0.9.17"
coil = "2.3.0"
redwood = "0.3.0-SNAPSHOT"
ktor = "2.2.4"
compose-navigation = "2.5.2"
compose-material3 = "1.1.0-alpha02"
dagger = "2.45"


[libraries]
anvil-gradle-plugin = { group = "com.squareup.anvil", name = "gradle-plugin", version.ref = "anvil" }
dagger-dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }


ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }


kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

xmlutil-serialization = 'io.github.pdvrieze.xmlutil:serialization:0.85.0'

dokkaPlugin = "org.jetbrains.dokka:dokka-gradle-plugin:1.8.10"
spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:6.17.0"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.25.1"
buildConfigPlugin = "com.github.gmazzo:gradle-buildconfig-plugin:3.1.0"
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.0" }
androidx-test-core = "androidx.test:core-ktx:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"

google-material = { module = "com.google.android.material:material", version = "1.8.0" }

jetbrains-compose-compiler = "org.jetbrains.compose.compiler:compiler:1.4.2"
jetbrains-compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jbCompose" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jbCompose" }
jetbrains-compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "jbCompose" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jbCompose" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jbCompose" }
jetbrains-compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "jbCompose" }
jetbrains-compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "jbCompose" }



androidGradlePlugin = { module = "com.android.tools.build:gradle", version = "7.4.2" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }
clikt = { module = "com.github.ajalt.clikt:clikt", version = "3.5.2" }
junit = { module = "junit:junit", version = "4.13.2" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.11" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
robolectric = { module = "org.robolectric:robolectric", version = "4.9.2" }
okio = { module = "com.squareup.okio:okio", version = "3.3.0" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version = "4.10.0" }
paging-compose-common = { module = "app.cash.paging:paging-compose-common", version = "3.2.0-alpha04-0.2.0" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version = "3.2.0-alpha04" }
zipline = { module = "app.cash.zipline:zipline", version.ref = "zipline" }
zipline-gradlePlugin = { module = "app.cash.zipline:zipline-gradle-plugin", version.ref = "zipline" }
zipline-loader = { module = "app.cash.zipline:zipline-loader", version.ref = "zipline" }
paparazzi-gradlePlugin = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version = "1.2.0" }
jimfs = "com.google.jimfs:jimfs:1.2"
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
turbine = "app.cash.turbine:turbine:0.12.3"




redwood-treehouse = { group = "app.cash.redwood", name = "redwood-treehouse", version.ref = "redwood" }
redwood-treehouse-host = { group = "app.cash.redwood", name = "redwood-treehouse-host", version.ref = "redwood" }
redwood-treehouse-lazylayout-api = { group = "app.cash.redwood", name = "redwood-treehouse-lazylayout-api", version.ref = "redwood" }
redwood-treehouse-lazylayout-compose = { group = "app.cash.redwood", name = "redwood-treehouse-lazylayout-compose", version.ref = "redwood" }
redwood-treehouse-lazylayout-schema = { group = "app.cash.redwood", name = "redwood-treehouse-lazylayout-schema", version.ref = "redwood" }
redwood-treehouse-guest = { group = "app.cash.redwood", name = "redwood-treehouse-guest", version.ref = "redwood" }
redwood-layout-schema = { group = "app.cash.redwood", name = "redwood-layout-schema", version.ref = "redwood" }
redwood-layout-widget = { group = "app.cash.redwood", name = "redwood-layout-widget", version.ref = "redwood" }
redwood-treehouse-lazylayout-widget = { group = "app.cash.redwood", name = "redwood-treehouse-lazylayout-widget", version.ref = "redwood" }
redwood-layout-compose = { group = "app.cash.redwood", name = "redwood-layout-compose", version.ref = "redwood" }
redwood-layout-compose-ui = { group = "app.cash.redwood", name = "redwood-layout-composeui", version.ref = "redwood" }
redwood-treehouse-lazylayout-compose-ui = { group = "app.cash.redwood", name = "redwood-treehouse-lazylayout-composeui", version.ref = "redwood" }
redwood-treehouse-compose-ui = { group = "app.cash.redwood", name = "redwood-treehouse-composeui", version.ref = "redwood" }
redwood-layout-widget-compose = { group = "app.cash.redwood", name = "redwood-layout-widget-compose", version.ref = "redwood" }

lint-core = { module = "com.android.tools.lint:lint", version.ref = "lint" }

cklib-gradle-plugin = { module = "co.touchlab:cklib-gradle-plugin", version = "0.2.4" }